# This file is used in the "dev" and "uat" environments to be able to test future and past campaigns
campaigns:

  compact_design:
    active: true
    start: "2019-10-06 10:00:00"

  address_type:
    active: false
    start: "2020-09-15"

  address_provision_options:
    active: true
    start: "2020-09-20"
    default_bucket: "provisional_address_options"

  confirmation_page_layout:
    active: true
    start: "2021-02-10"
    default_bucket: "new_layout"