# This file is used in the "dev" and "uat" environments to be able to test future and past campaigns
campaigns:

  address_type_steps:
    active: true
    start: "2022-11-01"
    default_bucket: "direct"
