monolog:
  handlers:
    main:
      type: error_log
      level: INFO
      channels: [ '!event', '!console' ]
    console:
      type: console
      process_psr_3_messages: false
      channels: [ '!event', '!doctrine', '!console' ]